[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_URL = "https://corporate-bingo-api.ryanwixon15.workers.dev"
  VITE_WS_URL = "wss://corporate-bingo-api.ryanwixon15.workers.dev"

[[headers]]
  for = "/index.html"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; connect-src 'self' wss://corporate-bingo.workers.dev https://corporate-bingo.workers.dev; img-src 'self' data:; font-src 'self'"
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/vite.svg"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"


# Proxy API requests to avoid CORS/SSL issues
[[redirects]]
  from = "/api/*"
  to = "https://corporate-bingo-api.ryanwixon15.workers.dev/api/:splat"
  status = 200
  force = true

# Redirect for SPA-like behavior (though we're using a single HTML file)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200