name = "jargon-api"
main = "worker/index.js"
compatibility_date = "2024-12-01"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "BingoRoom", "DashboardAnalytics" ]

[[migrations]]
tag = "v2"
new_sqlite_classes = [ "DecodeGame", "UserGames" ]

[[migrations]]
tag = "v3"
renamed_classes = [ { from = "DecodeGame", to = "Game" } ]

[vars]
CORS_ORIGIN = "https://playjargon.com"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "BingoRoom"

[[durable_objects.bindings]]
name = "ANALYTICS"
class_name = "DashboardAnalytics"

[[durable_objects.bindings]]
name = "GAMES"
class_name = "Game"

[[durable_objects.bindings]]
name = "USER_GAMES"
class_name = "UserGames"

[build]
command = ""

[env.production]
vars = { CORS_ORIGIN = "https://playjargon.com" }

[env.development]  
vars = { CORS_ORIGIN = "http://localhost:8080" }