name = "corporatebingo"
main = "worker.js"
compatibility_date = "2024-12-01"

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "BingoRoom", "DashboardAnalytics" ]

[vars]
CORS_ORIGIN = "https://corporate-bingo-ai.netlify.app"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "BingoRoom"

[[durable_objects.bindings]]
name = "ANALYTICS"
class_name = "DashboardAnalytics"

[build]
command = ""

[env.production]
vars = { CORS_ORIGIN = "https://corporate-bingo-ai.netlify.app" }

[env.development]  
vars = { CORS_ORIGIN = "http://localhost:8080" }