# Cloudflare Workers configuration for Multiplayer Buzzword Bingo

name = "buzzword-bingo-backend"
main = "src/backend/worker.ts"
compatibility_date = "2024-01-15"

# Worker settings
send_metrics = false

# Environment variables
[env.production]
name = "buzzword-bingo-prod"
vars = { CORS_ORIGINS = "https://engineer-memes.netlify.app,https://buzzword-bingo.com" }

[env.staging]
name = "buzzword-bingo-staging" 
vars = { CORS_ORIGINS = "https://staging-engineer-memes.netlify.app,http://localhost:5173" }

[env.development]
name = "buzzword-bingo-dev"
vars = { CORS_ORIGINS = "*", DEBUG = "true" }

# Durable Objects
[[durable_objects.bindings]]
name = "BINGO_ROOMS"
class_name = "BingoRoomObject"

[[durable_objects.migrations]]
tag = "v1"
new_classes = ["BingoRoomObject"]

# Resource limits
[limits]
cpu_ms = 50

# Build configuration
[build]
command = "npm run build:worker"
cwd = "."
watch_dir = "src/backend"

# Development settings
[dev]
port = 8787
local_protocol = "https"

# KV namespaces (for future features like global statistics)
# [[kv_namespaces]]
# binding = "BINGO_STATS"
# id = "your-kv-namespace-id"

# Analytics (optional)
# [analytics_engine_datasets]
# [[analytics_engine_datasets.bindings]]
# name = "BINGO_ANALYTICS"

# Custom domains (for production)
# [routes]
# routes = [
#   { pattern = "api.buzzword-bingo.com/*", zone_name = "buzzword-bingo.com" }
# ]