name: Deploy Corporate Bingo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Quality Assurance Pipeline
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Lint code
        run: npm run lint
        
      - name: Type checking
        run: npx tsc --noEmit
        
      - name: Build application
        run: npm run build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: corporate-bingo-build
          path: dist/
          retention-days: 30

  deploy-frontend:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    name: Trigger Netlify Build
    
    steps:
      - name: Trigger Netlify Build Hook
        run: |
          echo "🚀 Triggering Netlify build for commit ${{ github.sha }}"
          curl -X POST -d '{"commit": "${{ github.sha }}", "branch": "main"}' \
               -H "Content-Type: application/json" \
               ${{ secrets.NETLIFY_BUILD_HOOK }}
          echo "✅ Build hook triggered successfully"
          
      - name: Wait for Build to Start
        run: |
          echo "⏳ Waiting 30 seconds for build to initialize..."
          sleep 30

  notification:
    needs: [deploy-frontend]
    runs-on: ubuntu-latest
    if: always() && github.ref == 'refs/heads/main'
    name: Deployment Notification
    
    steps:
      - name: Deployment Success Notification
        if: needs.deploy-frontend.result == 'success'
        run: |
          echo "✅ Corporate Bingo deployed successfully!"
          echo "Frontend: https://corporate-bingo-ai.netlify.app"
          echo "Commit: ${{ github.sha }}"
          
      - name: Deployment Failure Notification
        if: needs.deploy-frontend.result == 'failure'
        run: |
          echo "❌ Corporate Bingo deployment failed!"
          echo "Check the logs for details"
          exit 1