name: Deploy Corporate Bingo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Quality Assurance Pipeline
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Lint code
        run: npm run lint
        
      - name: Type checking
        run: npx tsc --noEmit
        
      - name: Build application
        env:
          VITE_API_URL: https://corporatebingo.ryanwixon15.workers.dev
          VITE_WS_URL: wss://corporatebingo.ryanwixon15.workers.dev
        run: npm run build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: corporate-bingo-build
          path: dist/
          retention-days: 30

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    name: Deploy to Netlify
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies and build
        env:
          VITE_API_URL: https://corporatebingo.ryanwixon15.workers.dev
          VITE_WS_URL: wss://corporatebingo.ryanwixon15.workers.dev
        run: |
          npm ci
          npm run build
          
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "🚀 Deploy ${{ github.event.head_commit.message }} (${{ github.sha }})"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 10
          
      - name: Deployment Success Notification
        if: success()
        run: |
          echo "✅ Corporate Bingo deployed successfully!"
          echo "🌐 Frontend: https://corporate-bingo-ai.netlify.app"
          echo "📝 Commit: ${{ github.sha }}"
          echo "🎯 Cache-busting solution active - version tracking enabled"
          
      - name: Deployment Failure Notification
        if: failure()
        run: |
          echo "❌ Corporate Bingo deployment failed!"
          echo "🔍 Check the logs above for details"
          echo "💡 Common issues: Missing secrets, build errors, or Netlify API limits"
          exit 1