name: Deploy Corporate Bingo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '20'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Quality Assurance Pipeline
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Lint code
        run: npm run lint
        
      - name: Type checking
        run: npx tsc --noEmit
        
      - name: Build application
        run: npm run build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: corporate-bingo-build
          path: dist/
          retention-days: 30

  deploy-frontend:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    name: Deploy Frontend to Netlify
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        
      - name: Check build output
        run: |
          echo "Build completed, checking dist folder:"
          ls -la dist/
          echo "Build artifacts ready for deployment"
          
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Corporate Bingo deployment ${{ github.sha }}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  notification:
    needs: [deploy-frontend]
    runs-on: ubuntu-latest
    if: always() && github.ref == 'refs/heads/main'
    name: Deployment Notification
    
    steps:
      - name: Deployment Success Notification
        if: needs.deploy-frontend.result == 'success'
        run: |
          echo "✅ Corporate Bingo deployed successfully!"
          echo "Frontend: https://corporate-bingo-ai.netlify.app"
          echo "Commit: ${{ github.sha }}"
          
      - name: Deployment Failure Notification
        if: needs.deploy-frontend.result == 'failure'
        run: |
          echo "❌ Corporate Bingo deployment failed!"
          echo "Check the logs for details"
          exit 1